// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countOpenIssuesForUser = `-- name: CountOpenIssuesForUser :one
SELECT COUNT(*) FROM issues i
JOIN repos r ON r.id = i.repo_id
JOIN user_stars us ON us.repo_id = r.id
WHERE us.user_id = ?
  AND i.is_open = 1
`

func (q *Queries) CountOpenIssuesForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenIssuesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOpenIssuesForUser = `-- name: GetOpenIssuesForUser :many
SELECT i.id, i.github_id, i.repo_id, i.number, i.title, i.url, i.labels, i.is_open, i.created_at_github, i.updated_at_github, i.last_seen_at
FROM issues i
JOIN repos r ON r.id = i.repo_id
JOIN user_stars us ON us.repo_id = r.id
WHERE us.user_id = ?
  AND i.is_open = 1
ORDER BY i.updated_at_github DESC
LIMIT ?
OFFSET ?
`

type GetOpenIssuesForUserParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) GetOpenIssuesForUser(ctx context.Context, arg GetOpenIssuesForUserParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, getOpenIssuesForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.RepoID,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.Labels,
			&i.IsOpen,
			&i.CreatedAtGithub,
			&i.UpdatedAtGithub,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIssuesClosed = `-- name: MarkIssuesClosed :exec
UPDATE issues
SET is_open = 0
WHERE repo_id = ?
  AND is_open = 1
  AND github_id NOT IN (/*SLICE:open_github_ids*/?)
`

type MarkIssuesClosedParams struct {
	RepoID        int64
	OpenGithubIds []int64
}

func (q *Queries) MarkIssuesClosed(ctx context.Context, arg MarkIssuesClosedParams) error {
	query := markIssuesClosed
	var queryParams []interface{}
	queryParams = append(queryParams, arg.RepoID)
	if len(arg.OpenGithubIds) > 0 {
		for _, v := range arg.OpenGithubIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:open_github_ids*/?", strings.Repeat(",?", len(arg.OpenGithubIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:open_github_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const upsertIssue = `-- name: UpsertIssue :exec
INSERT INTO issues (github_id, repo_id, number, title, url, labels, is_open,
                    created_at_github, updated_at_github, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET
    title             = excluded.title,
    labels            = excluded.labels,
    is_open           = excluded.is_open,
    updated_at_github = excluded.updated_at_github,
    last_seen_at      = excluded.last_seen_at
`

type UpsertIssueParams struct {
	GithubID        int64
	RepoID          int64
	Number          int64
	Title           string
	Url             string
	Labels          sql.NullString
	IsOpen          int64
	CreatedAtGithub sql.NullTime
	UpdatedAtGithub sql.NullTime
	LastSeenAt      time.Time
}

func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) error {
	_, err := q.db.ExecContext(ctx, upsertIssue,
		arg.GithubID,
		arg.RepoID,
		arg.Number,
		arg.Title,
		arg.Url,
		arg.Labels,
		arg.IsOpen,
		arg.CreatedAtGithub,
		arg.UpdatedAtGithub,
		arg.LastSeenAt,
	)
	return err
}
