// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Issue struct {
	ID              int64
	GithubID        int64
	RepoID          int64
	Number          int64
	Title           string
	Url             string
	Labels          sql.NullString
	IsOpen          int64
	CreatedAtGithub sql.NullTime
	UpdatedAtGithub sql.NullTime
	LastSeenAt      time.Time
}

type Repo struct {
	ID            int64
	GithubID      int64
	FullName      string
	Description   sql.NullString
	Language      sql.NullString
	StarsCount    sql.NullInt64
	Etag          sql.NullString
	LastScannedAt sql.NullTime
	CreatedAt     time.Time
}

type User struct {
	ID             int64
	GithubID       int64
	GithubLogin    string
	EncryptedToken []byte
	CreatedAt      time.Time
	LastSyncedAt   sql.NullTime
}

type UserStar struct {
	UserID    int64
	RepoID    int64
	StarredAt sql.NullTime
}
