// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getReposToScan = `-- name: GetReposToScan :many
SELECT r.id, r.github_id, r.full_name, r.description, r.language, r.stars_count, r.etag, r.last_scanned_at, r.created_at
FROM repos r
WHERE r.last_scanned_at IS NULL
   OR r.last_scanned_at < ?
ORDER BY (
    SELECT COUNT(*) FROM user_stars us WHERE us.repo_id = r.id
) DESC
LIMIT ?
`

type GetReposToScanParams struct {
	LastScannedAt sql.NullTime
	Limit         int64
}

func (q *Queries) GetReposToScan(ctx context.Context, arg GetReposToScanParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, getReposToScan, arg.LastScannedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.FullName,
			&i.Description,
			&i.Language,
			&i.StarsCount,
			&i.Etag,
			&i.LastScannedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoScanned = `-- name: UpdateRepoScanned :exec
UPDATE repos SET etag = ?, last_scanned_at = ? WHERE id = ?
`

type UpdateRepoScannedParams struct {
	Etag          sql.NullString
	LastScannedAt sql.NullTime
	ID            int64
}

func (q *Queries) UpdateRepoScanned(ctx context.Context, arg UpdateRepoScannedParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoScanned, arg.Etag, arg.LastScannedAt, arg.ID)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos (github_id, full_name, description, language, stars_count)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET
    full_name   = excluded.full_name,
    description = excluded.description,
    language    = excluded.language,
    stars_count = excluded.stars_count
`

type UpsertRepoParams struct {
	GithubID    int64
	FullName    string
	Description sql.NullString
	Language    sql.NullString
	StarsCount  sql.NullInt64
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepo,
		arg.GithubID,
		arg.FullName,
		arg.Description,
		arg.Language,
		arg.StarsCount,
	)
	return err
}
