// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stars.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUserStarredRepos = `-- name: GetUserStarredRepos :many
SELECT r.id, r.github_id, r.full_name, r.description, r.language, r.stars_count, r.etag, r.last_scanned_at, r.created_at
FROM repos r
JOIN user_stars us ON us.repo_id = r.id
WHERE us.user_id = ?
`

func (q *Queries) GetUserStarredRepos(ctx context.Context, userID int64) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, getUserStarredRepos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.FullName,
			&i.Description,
			&i.Language,
			&i.StarsCount,
			&i.Etag,
			&i.LastScannedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUserToRepo = `-- name: LinkUserToRepo :exec
INSERT INTO user_stars (user_id, repo_id, starred_at)
VALUES (?, ?, ?)
ON CONFLICT(user_id, repo_id) DO NOTHING
`

type LinkUserToRepoParams struct {
	UserID    int64
	RepoID    int64
	StarredAt sql.NullTime
}

func (q *Queries) LinkUserToRepo(ctx context.Context, arg LinkUserToRepoParams) error {
	_, err := q.db.ExecContext(ctx, linkUserToRepo, arg.UserID, arg.RepoID, arg.StarredAt)
	return err
}
