// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, github_login, encrypted_token, created_at, last_synced_at FROM users WHERE github_id = ?
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const updateUserSyncedAt = `-- name: UpdateUserSyncedAt :exec
UPDATE users SET last_synced_at = ? WHERE id = ?
`

type UpdateUserSyncedAtParams struct {
	LastSyncedAt sql.NullTime
	ID           int64
}

func (q *Queries) UpdateUserSyncedAt(ctx context.Context, arg UpdateUserSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSyncedAt, arg.LastSyncedAt, arg.ID)
	return err
}

const updateUserToken = `-- name: UpdateUserToken :exec
UPDATE users SET encrypted_token = ? WHERE id = ?
`

type UpdateUserTokenParams struct {
	EncryptedToken []byte
	ID             int64
}

func (q *Queries) UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserToken, arg.EncryptedToken, arg.ID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (github_id, github_login, encrypted_token)
VALUES (?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET
    github_login     = excluded.github_login,
    encrypted_token  = excluded.encrypted_token
RETURNING id
`

type UpsertUserParams struct {
	GithubID       int64
	GithubLogin    string
	EncryptedToken []byte
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.GithubID, arg.GithubLogin, arg.EncryptedToken)
	var id int64
	err := row.Scan(&id)
	return id, err
}
